# Generated by Django 3.2.6 on 2021-09-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPadress', models.CharField(max_length=39)),
                ('county', models.CharField(max_length=15)),
                ('countycode', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('providertype', models.CharField(max_length=30)),
                ('ishosting', models.CharField(max_length=30)),
                ('isisp', models.CharField(max_length=30)),
                ('isvpn', models.CharField(max_length=30)),
                ('isproxy', models.CharField(max_length=30)),
                ('vpndomain', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpnconfig', models.BooleanField(default=False)),
                ('rdpcofig', models.BooleanField(default=False)),
                ('proxyconfig', models.BooleanField(default=False)),
                ('blockedmsgtitle', models.CharField(max_length=200)),
                ('blockedmsgbody', models.TextField(max_length=200)),
                ('allowedcountries', models.CharField(choices=[('Palestine', 'Palestine'), ('Japan', 'Japan'), ('Iceland', 'Iceland'), ('Singapore', 'Singapore')], max_length=15)),
                ('blockedcountries', models.CharField(choices=[('Palestine', 'Palestine'), ('Japan', 'Japan'), ('Iceland', 'Iceland'), ('Singapore', 'Singapore')], max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersetting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllVisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPadress', models.CharField(max_length=39)),
                ('county', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=20)),
                ('bot', models.BooleanField(default=False)),
                ('hosting', models.CharField(max_length=20)),
                ('providertype', models.CharField(max_length=20)),
                ('isblocked', models.BooleanField(default=False)),
                ('os', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uservisites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
